// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoKMU3qqVBUqMW5dA_f4DWEIlPzHtZdnY',
    appId: '1:860592582581:web:f57db14938abc4c7d0f3fc',
    messagingSenderId: '860592582581',
    projectId: 'my-notes-af0e5',
    authDomain: 'my-notes-af0e5.firebaseapp.com',
    storageBucket: 'my-notes-af0e5.appspot.com',
    measurementId: 'G-W2LY5TYBH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6I-0rlxuLl0z3UED0rargXg9p-CWC9SE',
    appId: '1:860592582581:android:2572f12f51dce478d0f3fc',
    messagingSenderId: '860592582581',
    projectId: 'my-notes-af0e5',
    storageBucket: 'my-notes-af0e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjv7fI04YBb6QEnZMQzfLHv2FbMHy8NzU',
    appId: '1:860592582581:ios:46219cfbde854ba5d0f3fc',
    messagingSenderId: '860592582581',
    projectId: 'my-notes-af0e5',
    storageBucket: 'my-notes-af0e5.appspot.com',
    iosClientId: '860592582581-adgtakre0dtfmtfk5vkp7s1jbecci268.apps.googleusercontent.com',
    iosBundleId: 'com.hady.dev.myNotes',
  );
}
